go go, powerrangers!
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
2013-06-29 13:46:36.112 (WARN ) [0x40000fd8c80] :498865:ibm.runjob.client.Job: terminated by signal 6
2013-06-29 13:46:36.112 (WARN ) [0x40000fd8c80] :498865:ibm.runjob.client.Job: abnormal termination by signal 6 from rank 8
done
